import { signS3Request, stampsFor } from '../backup/sigv4';

/**
 * Signing, checked against AWS's own worked example rather than against itself.
 *
 * A pinned signature generated by the implementation under test proves only that
 * it has not changed — including that it has not stopped being wrong. The vector
 * below is the one in AWS's "Signature Calculations for the Authorization
 * Header" documentation, with their example key, their example bucket and their
 * example timestamp, and the signature is the one they publish. That is what
 * makes this a conformance test.
 *
 * It was also confirmed live: the same code signed a `PUT`, a `LIST` and a
 * denied `GET` against the real bucket, which is the only check that covers the
 * parts a vector cannot — the host, the TLS, and the policy.
 */

const AWS_EXAMPLE = {
  accessKeyId: 'AKIAIOSFODNN7EXAMPLE',
  secretAccessKey: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
  region: 'us-east-1',
} as const;

const THEIR_MOMENT = Date.UTC(2013, 4, 24, 0, 0, 0);

function signatureOf(authorization: string): string {
  return authorization.split('Signature=')[1] ?? '';
}

it("matches AWS's published example signature", () => {
  const signed = signS3Request({
    method: 'GET',
    bucket: 'examplebucket',
    key: 'test.txt',
    // Their example predates regional endpoints, which is the only reason this
    // override exists; nothing in the app passes it.
    host: 'examplebucket.s3.amazonaws.com',
    body: new Uint8Array(),
    extraHeaders: { range: 'bytes=0-9' },
    credentials: AWS_EXAMPLE,
    now: THEIR_MOMENT,
  });

  expect(signatureOf(signed.headers.Authorization)).toBe(
    'f0e8bdb87c964420e857bd35b5d6ed310bd44f0170aba48dd91039c6036bdb41',
  );
});

it('names the region and the service in the credential scope', () => {
  const signed = signS3Request({
    method: 'PUT',
    bucket: 'somewhere',
    key: 'days/2026-01-05',
    body: new Uint8Array([1, 2, 3]),
    credentials: { ...AWS_EXAMPLE, region: 'ap-southeast-2' },
    now: THEIR_MOMENT,
  });

  expect(signed.headers.Authorization).toContain(
    'Credential=AKIAIOSFODNN7EXAMPLE/20130524/ap-southeast-2/s3/aws4_request',
  );
  expect(signed.url).toBe('https://somewhere.s3.ap-southeast-2.amazonaws.com/days/2026-01-05');
});

/**
 * The region belongs in the host, not in a redirect. S3 answers a wrong-region
 * request with a 301, and a redirect followed by `fetch` arrives with a
 * signature that no longer matches the request it is attached to.
 */
it('puts the region in the host', () => {
  const signed = signS3Request({
    method: 'GET',
    bucket: 'somewhere',
    body: new Uint8Array(),
    credentials: { ...AWS_EXAMPLE, region: 'eu-west-1' },
    now: THEIR_MOMENT,
  });

  expect(signed.headers.host).toBe('somewhere.s3.eu-west-1.amazonaws.com');
});

it('signs the body, so a changed byte cannot ride along', () => {
  const of = (body: Uint8Array) =>
    signatureOf(
      signS3Request({ method: 'PUT', bucket: 'b', key: 'k', body, credentials: AWS_EXAMPLE, now: THEIR_MOMENT }).headers
        .Authorization,
    );

  expect(of(new Uint8Array([1, 2, 3]))).not.toBe(of(new Uint8Array([1, 2, 4])));
});

/**
 * The storage class is a signed header, so the bucket sees the same one the app
 * chose. That matters here beyond correctness: the IAM policy only permits two
 * of them, so an unsigned or altered class is a 403 rather than a surprise on
 * the bill.
 */
it('covers the extra headers it is given', () => {
  const signed = signS3Request({
    method: 'PUT',
    bucket: 'b',
    key: 'media/x',
    body: new Uint8Array([1]),
    extraHeaders: { 'x-amz-storage-class': 'GLACIER_IR' },
    credentials: AWS_EXAMPLE,
    now: THEIR_MOMENT,
  });

  expect(signed.headers.Authorization).toContain(
    'SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-storage-class',
  );
});

it('encodes a key the way S3 does, not the way encodeURIComponent does', () => {
  const signed = signS3Request({
    method: 'PUT',
    bucket: 'b',
    // Every character here is left alone by `encodeURIComponent` and required
    // to be escaped by the specification.
    key: "note-audio/it's (a) recording!*",
    body: new Uint8Array(),
    credentials: AWS_EXAMPLE,
    now: THEIR_MOMENT,
  });

  expect(signed.url).toContain('note-audio/it%27s%20%28a%29%20recording%21%2A');
});

it('builds the two stamps SigV4 asks for', () => {
  expect(stampsFor(Date.UTC(2026, 7, 13, 9, 5, 3))).toEqual({
    amzDate: '20260813T090503Z',
    dateStamp: '20260813',
  });
});
